openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Biletado jwt pong"
  termsOfService: "http://biletado.gitlab.io/"
  contact:
    email: "dh@blaimi.de"
  license:
    name: "MIT"
    url: "http://biletado.gitlab.io/LICENSE.txt"
security:
  - biletado: []
paths:
  /jwt/:
    get:
      summary: returns the access token
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
