openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Biletado status"
  termsOfService: "http://biletado.gitlab.io/"
  contact:
    email: "dh@blaimi.de"
  license:
    name: "MIT"
    url: "http://biletado.gitlab.io/LICENSE.txt"
security:
  - biletado: []
paths:
  /status/:
    get:
      summary: returns information about the backend-service and status
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                properties:
                  supportedApis:
                    type: array
                    items:
                      type: string
                      enum:
                        - assets-v1
                        - jwt
                        - reservations-v1
                        - personal-v1
                        - status
                    minItems: 1
                  authors:
                    type: array
                    items:
                      type: string
                    minItems: 1
                required:
                  - supportedApis
