---
version: "2"
plugins:
  openapi:
    enabled: true
    files:
      - public/openapi/jwt.yaml
      - public/openapi/assets-v1.yaml
      - public/reservations-v1.yaml
      - public/personnel-v1.yaml
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: false
